
#ifdef __cplusplus
extern "C" {
#endif

#include "Resource/upCornor_20_10.c"
#include "Resource/back_24.c"
#include "Resource/check_24.c"
#include "Resource/cmd_24.c"
#include "Resource/connect_24.c"
#include "Resource/custom_24.c"
#include "Resource/delete_20_14.c"
#include "Resource/down_14_8.c"
#include "Resource/down_arrows_15_22.c"
#include "Resource/downCornor_20_10.c"
#include "Resource/extrude_24.c"
#include "Resource/fan_24.c"
#include "Resource/flow_24.c"
#include "Resource/folder_30_36.c"
#include "Resource/heatbed_20_12.c"
#include "Resource/heatbed_24.c"
#include "Resource/heatend_20_12.c"
#include "Resource/heatend_24.c"
#include "Resource/history_24.c"
#include "Resource/homeX_24.c"
#include "Resource/homeY_24.c"
#include "Resource/homeZ_24.c"
#include "Resource/keyPad_24.c"
#include "Resource/left_8_14.c"
#include "Resource/leftCornor_10_20.c"
#include "Resource/levelling_24.c"
#include "Resource/modelFile_30_36.c"
#include "Resource/motorOff_24.c"
#include "Resource/move_24.c"
#include "Resource/next_24.c"
#include "Resource/nextPage_28_16.c"
#include "Resource/opction_24.c"
#include "Resource/pause_24.c"
#include "Resource/pre_24.c"
#include "Resource/prePage_28_16.c"
#include "Resource/print_24.c"
#include "Resource/printing_24.c"
#include "Resource/rate_24.c"
#include "Resource/resume_24.c"
#include "Resource/right_8_14.c"
#include "Resource/rightCornor_10_20.c"
#include "Resource/save_16.c"
#include "Resource/save_24.c"
#include "Resource/setting_24.c"
#include "Resource/setting2_24.c"
#include "Resource/shutdown_16.c"
#include "Resource/shutdown_24.c"
#include "Resource/space_20_14.c"
#include "Resource/stop_24.c"
#include "Resource/temp_24.c"
#include "Resource/time_16.c"
#include "Resource/time_24.c"
#include "Resource/tool_24.c"
#include "Resource/up_14_8.c"
#include "Resource/up_arrows_15_22.c"
#include "Resource/home_34.c"
#include "Resource/upDown_34.c"
#include "Resource/splash_printer_64_68.c"
#include "Resource/splash_platform_64_3.c"
#include "Resource/splash_obj_28_16.c"
#include "Resource/splash_extrude_20_24.c"
#include "Resource/ok_24.c"


#include "Resource/xPosArc_107_34.c"
#include "Resource/xNegArc_107_34.c"
#include "Resource/yPosArc_107_34.c"
#include "Resource/yNegArc_107_34.c"
#include "Resource/zPosArc_82_27.c"
#include "Resource/zNegArc_82_27.c"


#include "Resource/microsoft_yahei_symbol_16.c"
#include "Resource/microsoft_yahei_ascii_16.c"
#ifdef FULL_CHINESE_FONT
#include "Resource/microsoft_yahei_chinese_16.c"
#else
#include "Resource/microsoft_yahei_chinese_small_16.c"
#endif

#ifdef __cplusplus
}
#endif
